name: NETLIFY DEMO 1 FEATURE

on:
  push:
    branches:
      - task/SDA-**
    paths:
      - demo1/**

jobs:
  build:
    env:
      JIRA_ISSUE_ID: ""
      DEPLOY_PREVIEW_URL: ""

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: echo git_branch
      run: |
        echo "::set-env name=JIRA_ISSUE_ID::$(echo $GITHUB_REF | grep -o -E 'SDA-[0-9]+' | grep -o -E '[0-9]+')"
    - name: netlify deployment
      env:
        NETLIFY_SITE_ID: ${{ secrets.DEMO1_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      run: |
        yarn
        yarn build:demo1
        echo "::set-env name=DEPLOY_PREVIEW_URL::$(npx netlify-cli deploy --dir=demo1/dist --message='feature $GITHUB_REF'| grep "Live Draft URL" |  grep -o -E 'https?://[^ ]+' )"

    - name: push JIRA comment
      run: |
        echo $JIRA_ISSUE_ID
        echo $DEPLOY_PREVIEW_URL
        curl --request POST \
          --url 'https://aharooms.atlassian.net/rest/api/3/issue/SDA-${{ env.JIRA_ISSUE_ID }}/comment' \
          --user 'tech@aharooms.com:${{ secrets.JIRA_AUTH_TOKEN }}' \
          --header 'Accept: application/json' \
          --header 'Content-Type: application/json' \
          --data '{
                    "visibility": {
                        "type": "role",
                        "value": "Administrators"
                    },
                    "body": {
                        "type": "doc",
                        "version": 1,
                        "content": [{
                            "type": "paragraph",
                            "content": [{
                                "text": "Preview Deploy SDA-${{ env.JIRA_ISSUE_ID }}",
                                "type": "text",
                                "marks": [{
                                    "type": "link",
                                    "attrs": {
                                        "href": "${{env.DEPLOY_PREVIEW_URL}}"
                                    }
                                }]
                            }]
                        }]
                    }
                }'
