name: NETLIFY DEMO 1 DEVELOP

on:
  push:
    branches:
      - develop
    paths:
      - demo1/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: echo git_branch
      run: |
        echo $GITHUB_REF
    - name: netlify deployment
      env:
        NETLIFY_SITE_ID: ${{ secrets.DEMO1_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      run: |
        yarn
        yarn build:demo1
        npx netlify-cli deploy --dir=demo1/dist --message='merged develop to prod' --prod | grep "Unique Deploy URL:"
